#!/usr/bin/env bash
counter=0
my_array=("Fix security vulnerability on installation"
                            "Update API documentation for version 2.0"
                            "Merge pull request #456:  optimizations"
                            "Add support for authentication"
                            "Refactor code for better maintainability"
                            "Implement new graphs"
                            "Release version 2.1.0"
                            "Update dependencies to latest versions"
                            "Resolve conflicts in feature branch"
                            "add single-city support"
                            "Improve error handling in API"
                            "Optimize mongodb queries"
                            "Standardize code formatting"
                            "Remove deprecated features"
                            "add emoji feature to single tweet composition"
                            "Update dependencies to latest versions"
                            "Implement some comment feedback"
                            "add multi-color theme change on graph themes"
                            "add multicity-samecountry support"
                            "Implement localization for multiple languages"
                            "Enhance API documentation"
                            "Implement automated code deployment, heroku"
                            "identify countries by their woeId"
                            "add logic to generate chart for cities in the same country"
                            "Update dependencies to latest versions"
                            "Enhance error reporting and logging"
                            "Fix issue with user authentication"
                           "add start tweet function"
                           "Update documentation for API endpoints"
                           "Merge pull request #13: Bug fixes"
                           "Refactor code for better performance"
                           "Address code review comments"
                           "Release version 2.0.0"
                           "Update dependencies"
                           "Resolve merge conflict"
                           "Test suite improvements"
                           "add multicity-multicountry support"
                           "Optimize database queries"
                           "Code style formatting changes"
                           "Remove deprecated functions"
                           "Improve user interface"
                           "Enhance error logging in the backend"
                           "Add unit tests for new features"
                           "Upgrade to the latest framework version"
                           "Update third-party libraries"
                           "randomize the tweets based on trends"
                           "Refactor schema for scalability"
                           "Add user feedback feature"
                           "Optimize asset loading"
                           "Fix memory leak in service"
                           "Add localization support for multiple languages"
                           "Enhance dev link automation"
                           "Add support for third-party providers"
                           "Enhance error reporting and logging"
                           "Optimize indexing for faster run"
                           "themes optimizations for base analyser"
                           "general start jobs for longer"
                           "dimension specification on wider assets"
                           "update build file with latest version"
                           "handle midmap for larger group")
random_hour_element=1
mn=$[ $RANDOM % 60 + 10 ]
sc=$[ $RANDOM % 60 + 10 ]

# Get the length of the array
array_length=${#my_array[@]}

# Define an array of integers
hour_array=(500 240 400 900 300)

# Get the length of the array
hour_array_length=${#hour_array[@]}


while [ $counter -le 2 ]
 do
      commit_counter=0
      commit_count_array=(0 2 5 13 0 1 0 1 2 4)
      commit_count_array_length=${#commit_count_array[@]}
      commit_count_index=$((RANDOM % commit_count_array_length))
      commit_count="${commit_count_array[commit_count_index]}"

      while [ $commit_counter -le $commit_count ]
       do
          # Generate a random index within the range of the array length
           random_index=$((RANDOM % array_length))
          # Get the element at the random index
          random_element="${my_array[random_index]}"

           dateUsed=$(gdate -d "2023-02-28 $random_hour_element hours $mn minutes $sc seconds" "+%a %b %d %H:%M:%S %Y %z")
           b="‘Indonesia’: [‘Jakarta’, ‘Surabaya’, ‘Bandung’, ‘Medan’, ‘Semarang’, ‘Bekasi’, ‘Tangerang’, ‘Depok’],
              ‘Italy’: [‘Rome’, ‘Milan’, ‘Naples’, ‘Venice’, ‘Florence’, ‘Turin’, ‘Bologna’, ‘Genoa’],
              ‘Japan’: [‘Tokyo’, ‘Osaka’, ‘Kyoto’, ‘Yokohama’, ‘Nagoya’, ‘Sapporo’, ‘Fukuoka’, ‘Kobe’]
            "
           c="${b} ${dateUsed}"
           echo $c > locations.js
           git add .
           git commit -m "$random_element"

           LC_ALL=C GIT_COMMITTER_DATE="$dateUsed" git commit --amend --no-edit --date "$dateUsed"

           mn=$(($[ $RANDOM % 60 + 10 ]))
           sc=$(($[ $RANDOM % 60 + 10 ]))

           commit_counter=$(($commit_counter + 1))
       done

  git push origin main -f

  counter=$(($counter + 1))

  # Generate a random index within the range of the array length

  random_hour_index=$((RANDOM % hour_array_length))
  # Get the element at the random index
  new_random_hour_element="${hour_array[random_hour_index]}"
  random_hour_element=$(($random_hour_element + $new_random_hour_element))

done
